GET http://localhost:3000/api/auth/users

###
GET http://localhost:3000/api/auth/users/1

###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"mdp"

}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"mdp"

}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"mdp"

}

###

POST http://localhost:3000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTYxMDQ1NTYwOSwiZXhwIjoxNjEwNTQyMDA5fQ.I_E7JNsLuhClcOsJI-xOHLEqargj2Y2KwU6d8sCrve4
Content-Type: application/json

{   
    "userId": "6",
    "text":"Text"

}

###
GET http://localhost:3000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTYxMDQ0ODU2MywiZXhwIjoxNjEwNTM0OTYzfQ.6cCzJDiv8GvdSssU9CoDE4BzVnwj43KhtKRZfsRuTVI
###

DELETE http://localhost:3000/api/articles/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwOTg0OTA5NiwiZXhwIjoxNjA5OTM1NDk2fQ.MFyIYgMZQAFBYAwSJTdxpnZWyrJFXW4AQ0692oreaT8

###

GET http://localhost:3000/api/articles/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwOTg0OTA5NiwiZXhwIjoxNjA5OTM1NDk2fQ.MFyIYgMZQAFBYAwSJTdxpnZWyrJFXW4AQ0692oreaT8

###

PUT http://localhost:3000/api/articles/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwOTg0OTA5NiwiZXhwIjoxNjA5OTM1NDk2fQ.MFyIYgMZQAFBYAwSJTdxpnZWyrJFXW4AQ0692oreaT8
Content-Type: application/json

{
    "text":"Text6"

}

