GET http://localhost:3000/api/auth/users

###
GET http://localhost:3000/api/auth/users/1

###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email":"test33@gmail.com",
    "password":"mdp"

}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"mdp"

}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"mdp"

}

###

POST http://localhost:3000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTYxMTMwMzkyNSwiZXhwIjoxNjExMzkwMzI1fQ.TfdQgr4OobS2zfE_i7Y1qVVO4LnJthblIrbiKGdqy2o
Content-Type: application/json

{   
    "userId": 6,
    "text":"Text"

}

###
GET http://localhost:3000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTYxMTMwMzgzOCwiZXhwIjoxNjExMzkwMjM4fQ.BT4dPKy8g_FbN2Wfv9ojlLcI0yW2CVLOonGBCUWo314
###

DELETE http://localhost:3000/api/articles/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwOTg0OTA5NiwiZXhwIjoxNjA5OTM1NDk2fQ.MFyIYgMZQAFBYAwSJTdxpnZWyrJFXW4AQ0692oreaT8

###

GET http://localhost:3000/api/articles/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwOTg0OTA5NiwiZXhwIjoxNjA5OTM1NDk2fQ.MFyIYgMZQAFBYAwSJTdxpnZWyrJFXW4AQ0692oreaT8

###

PUT http://localhost:3000/api/articles/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYwOTg0OTA5NiwiZXhwIjoxNjA5OTM1NDk2fQ.MFyIYgMZQAFBYAwSJTdxpnZWyrJFXW4AQ0692oreaT8
Content-Type: application/json

{
    "text":"Text6"

}

